server:
  address: 0.0.0.0  # Render требует привязку ко всем интерфейсам, иначе "No open ports detected"
  port: ${PORT:8080}

spring:
  datasource:
    url:  ${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

